In [1]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
np.random.rand(5)

array([0.89962917, 0.91470506, 0.90505539, 0.31241618, 0.67221592])

In [11]:
np.random.rand(5,5)

array([[0.20716575, 0.56521221, 0.69584955, 0.98104421, 0.40024301],
       [0.24368583, 0.75834411, 0.7503798 , 0.28323855, 0.02498269],
       [0.20872643, 0.22439988, 0.23620106, 0.45608687, 0.73416852],
       [0.56694513, 0.32249429, 0.46331479, 0.54852196, 0.9459181 ],
       [0.86536597, 0.87831562, 0.84462865, 0.42822309, 0.73557012]])

In [12]:
np.random.randn(2)

array([-0.05210914,  0.92828056])

In [13]:
np.random.randn(4,4)

array([[-1.07005108,  0.17187128, -1.11632186,  0.50258343],
       [-1.40520124, -0.46036052,  2.95414848,  1.18162295],
       [ 1.68098921, -2.00149817, -0.31574164,  0.40380726],
       [ 1.04804348, -0.47013597,  1.57739623, -0.48409117]])

In [14]:
np.random.randint(1,100)

79

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
ranarr = np.random.randint(0,50,10)

In [17]:
ranarr

array([ 6, 33, 14,  6, 49, 36, 10, 34,  9, 28])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ranarr.max()

np.int64(49)

In [20]:
ranarr.min()

np.int64(6)

In [21]:
ranarr.argmax()

np.int64(4)

In [22]:
ranarr.argmin()

np.int64(0)