In [25]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [26]:
import numpy as np

In [27]:
arr = np.array(my_list)

In [28]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [34]:
np.random.rand(5)

array([0.00519853, 0.94297455, 0.25504615, 0.92876247, 0.75440557])

In [35]:
np.random.rand(5,5)

array([[0.53477046, 0.17683061, 0.35810586, 0.74485983, 0.06864359],
       [0.35356616, 0.01894241, 0.34684454, 0.08486075, 0.56927189],
       [0.53701085, 0.50521205, 0.50083203, 0.57156688, 0.52791577],
       [0.46259748, 0.14066865, 0.6222274 , 0.11005113, 0.14187816],
       [0.46066662, 0.84817265, 0.44019886, 0.64894725, 0.03566997]])

In [36]:
np.random.randn(2)

array([-0.73458715, -1.7688275 ])

In [37]:
np.random.randn(4,4)

array([[-0.78398068, -1.05144857, -0.52670091,  0.99022143],
       [-0.23269724, -0.86316142,  0.37286305, -0.54004628],
       [-0.09134746, -2.65542173, -0.15783146,  0.94907337],
       [-1.39311877,  0.02230516, -0.2398139 , -0.42116867]])

In [38]:
np.random.randint(1,100)

68

In [39]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)

In [41]:
ranarr

array([17, 25,  5, 38, 49,  5, 30, 12, 49, 32])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr.max()

np.int64(49)

In [44]:
ranarr.min()

np.int64(5)

In [45]:
ranarr.argmax()

np.int64(4)

In [46]:
ranarr.argmin()

np.int64(2)